# Generated by Django 5.2.6 on 2025-10-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_of_measure',
            field=models.CharField(choices=[('pieces', 'Pieces'), ('packs', 'Packs'), ('boxes', 'Boxes'), ('kilograms', 'Kilograms'), ('grams', 'Grams'), ('liters', 'Liters'), ('meters', 'Meters'), ('units', 'Units'), ('pairs', 'Pairs'), ('sets', 'Sets'), ('bottles', 'Bottles'), ('cartons', 'Cartons'), ('bags', 'Bags')], default='pieces', max_length=20),
        ),
    ]
